### ISSUE TITLE
To-Do :  Bonn Visit  2017

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#116]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

### To Do for Donna and Carsten, Bonn 2017

- [x] vtkout settings?  (Got rid of vtk_debug )
        -- cleaned these up - vtkout now matches other output methods
- [x]  Quiet exit from Option checking?
- [x]  Levels of timing output
- [x] Makefile.apps - local copy ? 
- [x] dist version (.tar.gz) doesn't include any non-compile code (.ini files, *.m files, etc)
- [x] torthem ?  How should this be updated?  
- [x] Smooth refine for initial refinement
- [x] Bug in timing output?  See issue #117
- [x] BSD vs. GPL license?
- [x] SPACE_DIM, PATCH_DIM, etc

See Boise visit 2018
- [ ] vtkout for shockbubble different quadrants solution
       -- Included in 2018 to-do
- [ ] Static IDs for virtual tables? 
- [ ] p8est?  (what is the best way to organize files?)

Ignore for now
- [ ] p6est for Ash cloud modeling

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/116

**Comment by donnaaboise** [comment]
All options have either been done or moved to new ToDo list ...
