### ISSUE TITLE
To-Do : Boise Visit 2018

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#120]
To Do for Donna and Carsten, Boise 2018

- [ ]   vtkout for shockbubble different quadrants solution
- [ ]   p8est? (what is the best way to organize files?)
- [ ]  Static IDs for virtual tables?
- [ ] Add CUDA support for build system
- [ ] Periodic boundary conditions for five patch grid
